kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cityweatheroperator
subjects:
- kind: ServiceAccount
  name: cityweatheroperator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cityweatheroperator
  apiGroup: rbac.authorization.k8s.io
