apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cityweathers.xabaril.io
spec:
  group: xabaril.io
  names:
    plural: cityweathers
    singular: cityweather
    kind: cityweather
    listKind: cityweathers
    shortNames:
      - cw
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            city:
              type: string
            replicas:
              type: integer
          required:
            - city
